name: Ruby
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  regression_tests:
    timeout-minutes: 3
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        ruby:
          - "3.2"
          - "3.3"
          - "3.4"
        gemfile:
          - "puma-6-latest"
          - "puma-6.5-latest"
          - "puma-7-latest"
    runs-on: ${{ matrix.os }}
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec appraisal ${{ matrix.gemfile }} rake
