name: Ruby
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  macos_regression:
    runs-on: macos-latest
    timeout-minutes: 3
    strategy:
      matrix:
        ruby:
          - "3.2"
          - "3.3"
          - "3.4"
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
  ubuntu_regression:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    strategy:
      matrix:
        ruby:
          - "3.2"
          - "3.3"
          - "3.4"
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
